// Generated by CoffeeScript 1.10.0
(function() {
  var onReady;

  onReady = function() {
    var goalText, setDownTextAreText, url, urlsT, win;
    urlsT = $('.floor-wrap>div.bd:first a:first');
    if (urlsT.length === 0 || urlsT.attr('href').indexOf('try.taobao.com/report/report_detail.htm') === -1) {
      callBackT(null, 'no efficacious link');
      close();
    }
    url = urlsT != null ? urlsT.attr('href') : void 0;
    window.scrollTo(0, document.body.scrollHeight);
    goalText = '';
    $('#submitBtn').on('click', function() {
      return setTimeout(function() {
        callBackT(null, goalText);
        return close();
      }, 1000);
    });
    win = open(url);
    win.setDownTextAreText = setDownTextAreText;
    return setDownTextAreText = function(text) {
      var textT;
      textT = text + ',麻烦回赞，' + $('.goalUrlM', opener.document).val().trim();
      $($('iframe')[0].contentWindow.document.getElementById('editorbodyid')).text(textT);
      return goalText = textT;
    };
  };

  myCommonToolsZ.fireActionByCusCondition(function() {
    return $('.floor-wrap>div.bd a:first').length !== 0;
  }, function() {
    return onReady();
  });

}).call(this);

//# sourceMappingURL=certainItemContent.js.map
