// Generated by CoffeeScript 1.10.0
(function() {
  var onReady;

  onReady = function() {
    var textT;
    window.scrollTo(0, document.body.scrollHeight);
    textT = "很好的报告哦~" + (myCommonToolsZ.repeatStr('~', (Math.random() * 10).toFixed()));
    textT = textT.trim();
    setTimeout(function() {
      $('.f-txt').val(textT);
      $('.J_PostComment')[0].click();
      return $('.J_Dig')[0].click();
    }, 500);
    return myCommonToolsZ.fireActionByCusCondition(function() {
      var t;
      t = $('.comment-list>li:first .words');
      return t.length !== 0 && t.text().trim().indexOf(textT) !== -1;
    }, function() {
      var sayer, setStrT;
      sayer = $('.comment-list>li:first .words>a').text().trim();
      $('.comment-list>li:first .words>a').remove();
      setStrT = function() {
        var backText;
        backText = $('.J_CancelDig').text().trim() + ',' + $('.comment-list>li:first .words').text().trim() + ' @' + $('.comment-list>li:first .time').text().trim() + ' by ' + sayer;
        chrome.extension.sendMessage({
          type: 'doComm',
          data: backText
        });
        return setTimeout(function() {
          return close();
        }, 1000);
      };
      return myCommonToolsZ.fireActionByCusCondition(function() {
        return $('.J_CancelDig').length !== 0 && $('.comment-list>li:first .words').length !== 0 && $('.comment-list>li:first .time').length !== 0;
      }, setStrT);
    });
  };

  myCommonToolsZ.fireActionByCusCondition(function() {
    return $('.J_Dig').length !== 0 && $('.J_PostComment').length !== 0;
  }, function() {
    return onReady();
  });

}).call(this);

//# sourceMappingURL=certainCommont.js.map
