// Generated by CoffeeScript 1.10.0
(function() {
  var goalUrl, onReady, setDownTextAreTextMain;

  setDownTextAreTextMain = null;

  goalUrl = localStorage.getItem('goalUrl');

  onReady = function() {
    var goalText, setDownTextAreText, url, urlsT, win;
    urlsT = $('.floor-wrap>div.bd:first a:first');
    if (urlsT.length === 0 || urlsT.attr('href').indexOf('try.taobao.com/report/report_detail.htm') === -1) {
      close();
      return;
    }
    url = urlsT != null ? urlsT.attr('href') : void 0;
    window.scrollTo(0, document.body.scrollHeight);
    goalText = '';
    $('#submitBtn').on('click', function() {
      return setTimeout(function() {
        chrome.extension.sendMessage({
          type: 'certToMain',
          data: goalText
        });
        return close();
      }, 1000);
    });
    win = open(url);
    chrome.extension.sendMessage({
      type: 'cert'
    });
    setDownTextAreText = function(text) {
      var textT;
      textT = text + ',麻烦回赞，' + goalUrl;
      $($('iframe')[0].contentWindow.document.getElementById('editorbodyid')).text(textT);
      goalText = textT;
      return setTimeout(function() {
        return $('#submitBtn')[0].click();
      }, 1000);
    };
    return setDownTextAreTextMain = setDownTextAreText;
  };

  myCommonToolsZ.fireActionByCusCondition(function() {
    return $('.floor-wrap>div.bd a:first').length !== 0;
  }, function() {
    return onReady();
  });

  $('body').prepend('<input type="text" id="goalUrlText"></input>');

  myCommonToolsZ.insertBtn('save', function() {
    return localStorage.setItem('goalUrl', $('#goalUrlText').val());
  });

  chrome.extension.onMessage.addListener(function(obj) {
    if (obj.action === 'doCert') {
      return setDownTextAreTextMain(obj.data);
    }
  });

}).call(this);

//# sourceMappingURL=certainItemContent.js.map
