// Generated by CoffeeScript 1.10.0
(function() {
  var addCB, callBackMain, main, onReady;

  callBackMain = function() {};

  onReady = function() {
    var effectiveUrls, ele, fn, i, len, mainItems;
    mainItems = $('table.posts:eq(1) tr>td.subject');
    effectiveUrls = [];
    fn = function(ele) {
      if ($(ele).find('.myPickCb')[0]['checked'] && $(ele).find('a').attr('href') !== '') {
        return effectiveUrls.push($(ele).find('a').attr('href'));
      }
    };
    for (i = 0, len = mainItems.length; i < len; i++) {
      ele = mainItems[i];
      fn(ele);
    }
    return async.mapLimit(effectiveUrls, 1, function(url, callback) {
      var w;
      w = open(url);
      chrome.extension.sendMessage({
        type: 'main'
      });
      return callBackMain = callback;
    }, function(err, result) {
      return $("body").prepend("done,count is " + result.length);
    });
  };

  addCB = function() {
    $('table.posts:eq(1) tr:first').remove();
    $('table.posts:eq(1) tr .subject>.detail').after(' <input type="checkbox" class="myPickCb"/> ');
    $('table.posts:eq(1) tr .subject>.detail').after('<button class="openC">open</button>');
    return setTimeout(function() {
      return $('.openC').on('click', function() {});
    }, 500);
  };

  main = function() {
    $("body").prepend('<button id = "myActionBtn">action</button>');
    $("body").prepend('<input type="text" class="goalUrlM" />');
    return setTimeout(function() {
      return $('button#myActionBtn').on('click', function() {
        return onReady();
      });
    }, 3000);
  };

  main();

  myCommonToolsZ.fireActionByCusCondition(function() {
    return $('table.posts:eq(1) tr:first').length !== 0;
  }, function() {
    return addCB();
  });

  chrome.extension.onMessage.addListener(function(obj) {
    if (obj.action === 'doCertToMain') {
      return callBackMain(null, obj.data);
    }
  });

}).call(this);

//# sourceMappingURL=mainListContent.js.map
