// Generated by CoffeeScript 1.10.0
(function() {
  window.myCommonToolsZ = {
    fireActionAtDomAppear: function(selector, action, delay) {
      if (delay == null) {
        delay = 100;
      }
      return $('body').on('DOMSubtreeModified', function() {
        if ($(selector).length !== 0) {
          return setTimeout(function() {
            return action($(selector));
          }, delay);
        }
      });
    },
    fireActionInCondition: function(condtionF, action, delay) {
      if (delay == null) {
        delay = 100;
      }
      return $('body').on('DOMSubtreeModified', function() {
        if (condtionF.call()) {
          return setTimeout(function() {
            return action.call();
          }, delay);
        }
      });
    },
    fireActionByCusCondition: function(condtionF, action, interval, delay) {
      var idT;
      if (interval == null) {
        interval = 100;
      }
      if (delay == null) {
        delay = 100;
      }
      return idT = setInterval(function() {
        if (condtionF()) {
          clearInterval(idT);
          return setTimeout(function() {
            return action();
          }, delay);
        }
      }, interval);
    },
    repeatStr: function(str, times) {
      var gStrs;
      if (times == null) {
        times = 2;
      }
      gStrs = [];
      while (times--) {
        gStrs.push(str);
      }
      return gStrs.join("");
    },
    insertBtn: function(text, action) {
      var idT;
      idT = "myActionBtn" + new Date().getTime();
      $("body").prepend('<button id = ' + idT + '>' + text + '</button>');
      return setTimeout(function() {
        return $('#' + idT).on('click', action);
      }, 500);
    }
  };

}).call(this);

//# sourceMappingURL=myCommonToolsZ.js.map
