// Generated by CoffeeScript 1.10.0
(function() {
  setTimeout(function() {
    chrome.extension.sendMessage({
      type: 'certToMain',
      data: 'normal close'
    });
    return close();
  }, 500);

}).call(this);

//# sourceMappingURL=selfClose.js.map
